"""Build wojak_index.json: a tree index of wojack_source_images/.

The index feeds the TypeSafe (jev) classifier, which caps Choice questions at
255 options. With 640+ images the classifier walks the tree: at each node it
answers one Choice over the child names; image leaves end the walk.

  group node: {"name": str, "children": [...]}
  image leaf: {"name": str, "path": str, "description": str}

Leaf descriptions are one sentence each, generated by a vision model
(ember-1 via Fireworks) for leaves that don't have one yet. Re-running is
incremental: existing descriptions are kept, only new/undescribed images
hit the API. Failures are skipped and picked up on the next run.

Usage:
  python3 build_index.py            # describe any leaves missing one
  python3 build_index.py --limit 3  # smoke test: describe at most 3

Env (from .env or environment): FIREWORKS_API_KEY, VISION_LLM_MODEL.
"""

import argparse
import base64
import json
import os
import re
import subprocess
import tempfile
import time
import urllib.error
import urllib.request
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

ROOT = Path(__file__).parent
SOURCE = ROOT / "wojack_source_images"
# Default output is the gitignored full index. The committed wojak_index.json
# is the curated SFW set produced by curate_index.py; never overwrite it here.
DEFAULT_OUT = "wojak_index.full.json"

IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".webp"}
MIME = {".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
        ".webp": "image/webp"}

API_URL = "https://api.fireworks.ai/inference/v1/chat/completions"
DOWNSCALE_OVER_BYTES = 4 * 1024 * 1024  # keep base64 payloads small
WORKERS = 8
ATTEMPTS = 3
CHECKPOINT_EVERY = 25

PROMPT = ("Describe this wojak meme image in exactly one sentence. Cover the "
          "character, their emotion, and what they are doing or what is "
          "distinctive about them.")


def load_env() -> None:
    env_file = ROOT / ".env"
    if not env_file.exists():
        return
    for line in env_file.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            os.environ.setdefault(key.strip(), value.strip())


def humanize(stem: str) -> str:
    """AngryWojak -> Angry Wojak; wojak-browsing-internet -> wojak browsing internet."""
    s = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", stem)  # camelCase split
    s = re.sub(r"[_\-]+", " ", s)  # snake/kebab split
    s = re.sub(r"\s+", " ", s).strip()
    return s


def build_group(dir_path: Path) -> dict | None:
    children = []
    for p in sorted(dir_path.iterdir(), key=lambda x: (not x.is_dir(), x.name.lower())):
        if p.is_dir():
            node = build_group(p)
            if node:  # skip dirs with no images
                children.append(node)
        elif p.suffix.lower() in IMAGE_EXTS:
            children.append({
                "name": humanize(p.stem),
                "path": str(p.relative_to(SOURCE)),
            })

    if not children:
        return None

    # Names become Choice option ids, so siblings must be unique.
    counts = Counter(c["name"] for c in children)
    seen: Counter[str] = Counter()
    for c in children:
        if counts[c["name"]] > 1:
            seen[c["name"]] += 1
            if seen[c["name"]] > 1:
                c["name"] = f"{c['name']} ({seen[c['name']]})"
    names = [c["name"] for c in children]
    dupes = [n for n, c in Counter(names).items() if c > 1]
    if dupes:
        raise SystemExit(f"name collisions in {dir_path}: {dupes}")

    return {"name": dir_path.name, "children": children}


def leaves(node: dict):
    if "path" in node:
        yield node
    else:
        for c in node["children"]:
            yield from leaves(c)


def image_payload(path: Path) -> str:
    """base64 data URI; downscales oversized images via sips (macOS)."""
    if path.stat().st_size > DOWNSCALE_OVER_BYTES:
        tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
        tmp.close()
        try:
            subprocess.run(
                ["sips", "-Z", "1024", "-s", "format", "png",
                 str(path), "--out", tmp.name],
                check=True, capture_output=True)
            data = Path(tmp.name).read_bytes()
        finally:
            Path(tmp.name).unlink(missing_ok=True)
        return f"data:image/png;base64,{base64.b64encode(data).decode()}"
    data = base64.b64encode(path.read_bytes()).decode()
    return f"data:{MIME[path.suffix.lower()]};base64,{data}"


def describe(path: Path, api_key: str, model: str) -> str:
    body = json.dumps({
        "model": model,
        "max_tokens": 1024,
        "messages": [{"role": "user", "content": [
            {"type": "text", "text": PROMPT},
            {"type": "image_url", "image_url": {"url": image_payload(path)}},
        ]}],
    }).encode()

    last_err = "unknown"
    for attempt in range(ATTEMPTS):
        req = urllib.request.Request(API_URL, data=body, headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        })
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                payload = json.loads(resp.read())
            text = (payload["choices"][0]["message"].get("content") or "").strip()
            if text:
                # house style: no em/en dashes in anything we ship
                return text.replace("—", " - ").replace("–", "-")
            last_err = "empty content"
        except urllib.error.HTTPError as e:
            last_err = f"HTTP {e.code}"
            if e.code not in (429, 500, 502, 503, 504):
                break  # 4xx other than 429 won't fix itself
        except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as e:
            last_err = str(e)
        time.sleep(2 ** attempt)
    raise RuntimeError(f"{path.name}: {last_err}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--limit", type=int, default=None,
                        help="describe at most N images (smoke test)")
    parser.add_argument("--out", default=DEFAULT_OUT,
                        help=f"index to write (default {DEFAULT_OUT})")
    args = parser.parse_args()
    out = ROOT / args.out

    load_env()
    tree = build_group(SOURCE)
    assert tree is not None
    tree["name"] = "wojaks"

    # Carry forward existing descriptions so re-runs are incremental.
    existing = {}
    if out.exists():
        old = json.loads(out.read_text())
        existing = {l["path"]: l["description"] for l in leaves(old)
                    if l.get("description")}
    all_leaves = list(leaves(tree))
    kept = 0
    for l in all_leaves:
        desc = existing.get(l["path"])
        if desc:
            l["description"] = desc
            kept += 1
    missing = [l for l in all_leaves if "description" not in l]
    if args.limit is not None:
        missing = missing[:args.limit]
    print(f"{len(all_leaves)} wojaks, {kept} descriptions kept, "
          f"{len(missing)} to describe")

    if missing:
        api_key = os.environ.get("FIREWORKS_API_KEY")
        model = os.environ.get("VISION_LLM_MODEL",
                               "accounts/fireworks/models/ember-1")
        if not api_key:
            raise SystemExit("FIREWORKS_API_KEY not set")

        done = 0
        failed = []

        def work(leaf):
            return leaf, describe(SOURCE / leaf["path"], api_key, model)

        with ThreadPoolExecutor(max_workers=WORKERS) as pool:
            futures = {pool.submit(work, l): l for l in missing}
            for fut in as_completed(futures):
                leaf = futures[fut]
                try:
                    _, text = fut.result()
                    leaf["description"] = text
                    done += 1
                except Exception as e:
                    failed.append(f"{leaf['path']}: {e}")
                if done and done % CHECKPOINT_EVERY == 0:
                    out.write_text(json.dumps(tree, indent=2,
                                              ensure_ascii=False) + "\n")
                    print(f"  checkpoint: {done}/{len(missing)} described")
        if failed:
            print(f"{len(failed)} failed (retry on next run):")
            for f in failed:
                print(f"  {f}")

    out.write_text(json.dumps(tree, indent=2, ensure_ascii=False) + "\n")
    described = sum(1 for l in all_leaves if l.get("description"))
    print(f"wrote {out.name}: {described}/{len(all_leaves)} described")


if __name__ == "__main__":
    main()
